#!/bin/bash
dnf update -y
dnf install -y nodejs
mkdir -p /opt/app
echo "Y29uc3QgZXhwcmVzcyA9IHJlcXVpcmUoJ2V4cHJlc3MnKQpjb25zdCB7IFMzQ2xpZW50LCBHZXRPYmplY3RDb21tYW5kIH0gPSByZXF1aXJlKCdAYXdzLXNkay9jbGllbnQtczMnKQpjb25zdCBhcHAgPSBleHByZXNzKCkKY29uc3QgczMgPSBuZXcgUzNDbGllbnQoeyByZWdpb246IHByb2Nlc3MuZW52LkFXU19SRUdJT04gfSkKY29uc3QgQlVDS0VUID0gcHJvY2Vzcy5lbnYuQlVDS0VUX05BTUUKY29uc3QgUE9SVCA9IHByb2Nlc3MuZW52LlBPUlQgfHwgMzAwMApjb25zdCBzdHJlYW1Ub1N0cmluZyA9IHN0cmVhbSA9PgogIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAgIGNvbnN0IGNodW5rcyA9IFtdCiAgICBzdHJlYW0ub24oJ2RhdGEnLCBjID0+IGNodW5rcy5wdXNoKGMpKQogICAgc3RyZWFtLm9uKCdlcnJvcicsIHJlamVjdCkKICAgIHN0cmVhbS5vbignZW5kJywgKCkgPT4gcmVzb2x2ZShCdWZmZXIuY29uY2F0KGNodW5rcykudG9TdHJpbmcoJ3V0Zi04JykpKQogIH0pCmFwcC5nZXQoJy8nLCBhc3luYyAocmVxLCByZXMpID0+IHsKICB0cnkgewogICAgY29uc3QgZGF0YSA9IGF3YWl0IHMzLnNlbmQoCiAgICAgIG5ldyBHZXRPYmplY3RDb21tYW5kKHsgQnVja2V0OiBCVUNLRVQsIEtleTogJ3NoYXJlZC50eHQnIH0pCiAgICApCiAgICBjb25zdCBjb250ZW50ID0gYXdhaXQgc3RyZWFtVG9TdHJpbmcoZGF0YS5Cb2R5KQogICAgcmVzLnNlbmQoYDxoMT5WaWV3ZXI8L2gxPjxwcmU+JHtjb250ZW50fTwvcHJlPjxhIGhyZWY9Ii8iPlJlZnJlc2g8L2E+YCkKICB9IGNhdGNoIChlcnIpIHsKICAgIHJlcy5zZW5kKAogICAgICAnPGgxPlZpZXdlcjwvaDE+PHA+Tm8gZmlsZSB1cGxvYWRlZCB5ZXQuPC9wPjxhIGhyZWY9Ii8iPlJlZnJlc2g8L2E+JwogICAgKQogIH0KfSkKYXBwLmxpc3RlbihQT1JULCAoKSA9PiBjb25zb2xlLmxvZyhgVmlld2VyIGxpc3RlbmluZyBvbiAke1BPUlR9YCkpCg==" | base64 -d > /opt/app/app.js
echo "ewogICJuYW1lIjogInZpZXdlci1hcHAiLAogICJ2ZXJzaW9uIjogIjEuMC4wIiwKICAibWFpbiI6ICJhcHAuanMiLAogICJkZXBlbmRlbmNpZXMiOiB7CiAgICAiZXhwcmVzcyI6ICJeNC4xOS4yIiwKICAgICJAYXdzLXNkay9jbGllbnQtczMiOiAiXjMuNjAwLjAiCiAgfQp9Cg==" | base64 -d > /opt/app/package.json
cd /opt/app
npm install --omit=dev
cat > /etc/systemd/system/viewer.service << 'SERVICE'
[Unit]
Description=Viewer App
After=network.target

[Service]
Environment=BUCKET_NAME=itmo-444-544-jbenman-fileshare
Environment=AWS_REGION=us-east-2
Environment=PORT=3000
WorkingDirectory=/opt/app
ExecStart=/usr/bin/node /opt/app/app.js
Restart=always
User=ec2-user

[Install]
WantedBy=multi-user.target
SERVICE
chown -R ec2-user:ec2-user /opt/app
systemctl daemon-reload
systemctl enable viewer.service
systemctl start viewer.service
